#!/bin/bash
LOCKFILE="/tmp/mic_mute.lock"
if [ -e "$LOCKFILE" ]; then exit 0; fi
touch "$LOCKFILE"

wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# Update the hardware LED
if wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep -q "\[MUTED\]"; then
    brightnessctl --device='platform::micmute' set 1 >/dev/null 2>&1
else
    brightnessctl --device='platform::micmute' set 0 >/dev/null 2>&1
fi

sleep 0.2
rm -f "$LOCKFILE"
