#!/bin/bash
updates=$(checkupdates 2>/dev/null | wc -l)
if [ "$updates" -gt 0 ]; then
    echo "{\"text\": \"$updates 󰚰\", \"tooltip\": \"$updates pending updates\"}"
else
    echo "{\"text\": \"\", \"tooltip\": \"System up to date\"}"
fi
