[colors-dark]
alpha=0.95
background=1a120d
foreground=f0dfd7

## Normal/regular colors (color0-color7)
regular0=1a120d
regular1=ffb4ab
regular2=e5bfaa
regular3=ccc992
regular4=ffb68c
regular5=4a481d
regular6=5c4131
regular7=f0dfd7

## Bright colors (color8-color15)
bright0=3d332d
bright1=93000a
bright2=e5bfaa
bright3=ccc992
bright4=ffb68c
bright5=e8e5ac
bright6=ffdbc9
bright7=ffdbc9
