include=~/.config/foot/colors.ini

[main]
shell=/usr/bin/zsh
font=JetBrains Mono:size=12.1
pad=15x15 center
resize-by-cells=no

[csd]
# Disable client-side decorations since Niri handles borders
preferred=none
