include=~/.config/foot/colors.ini

[main]
shell=/usr/bin/zsh
font=JetBrainsMono Nerd Font:size=12.1
pad=15x15 center
resize-by-cells=no

[csd]
# Disable client-side decorations since Niri handles borders
preferred=none

[text-bindings]
\x1b[27;5;9~ = Control+Tab
\x1b[27;6;9~ = Control+Shift+Tab Control+ISO_Left_Tab Control+Shift+ISO_Left_Tab

