[colors-dark]
alpha=0.95
background=2e2428
foreground=d2d0da
cursor=9B6E71 2e2428
selection-foreground=2e2428
selection-background=9B6E71
urls=9B6E71

## Normal/regular colors (color0-color7)
regular0=2e2428
regular1=9B6E71
regular2=6C748D
regular3=8F7B88
regular4=9B6E71
regular5=A496A4
regular6=CEB0B3
regular7=d2d0da

## Bright colors (color8-color15)
bright0=939198
bright1=9B6E71
bright2=6C748D
bright3=8F7B88
bright4=8A889D
bright5=A496A4
bright6=CEB0B3
bright7=d2d0da
