# BACKGROUND
background {
    monitor =
    path = ~/Wallpapers/4000x4000_static.jpg
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.05
}

general {
    no_fade_in = false
    no_fade_out = false
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(200, 200, 200, 1.0)
    font_size = 90
    font_family = Roboto Black

    position = 0, 80
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B %Y")"
    color = rgba(200, 200, 200, 0.8)
    font_size = 22
    font_family = Roboto

    position = 0, -20
    halign = center
    valign = center
}

# GREETING
label {
    monitor =
    text = Hi there, $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 25
    font_family = Roboto

    position = 0, -80
    halign = center
    valign = center
}

# PASSWORD INPUT FIELD
input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15
    placeholder_text = <i>Enter Password...</i>

    position = 0, -160
    halign = center
    valign = center
}
